#include "script_component.hpp"

class CfgPatches {
    class COMPONENT_GENERAL {
        author="KJW";
        requiredAddons[]=
        {
            "A3_Data_F",
            "A3_Weapons_F",
            "A3_Characters_F",
            "A3_Data_F_AoW_Loadorder",
            "USP_Gear_Face"
        };
        skipWhenMissingDependencies=1;
        requiredVersion=1;
		units[] = {""};
		weapons[] = {""};
		vehicles[] = {""};
	};
};

class CfgWeapons {
    // Uniform items, Guns, Helmets, NVGs, Vests

    // Class declarations
    class ItemCore;
    class H_HelmetB;

    COMPAT(USP_PELTOR_COMTAC3,ItemCore,0.5)
    COMPAT(USP_PELTOR_COMTAC3_OFF,ItemCore,0.5)
    COMPAT(USP_A2_BANDANA,ItemCore,0)
    COMPAT(USP_A2_BANDANA_DC,ItemCore,0)
    COMPAT(USP_THM_BEANIE,ItemCore,0)
    COMPAT(USP_THM_BEANIE_DC,ItemCore,0)
    COMPAT(USP_A2_BOONIE_HAT,ItemCore,0.8)
    COMPAT(USP_PAKOL_HAT,H_HelmetB,0)
    COMPAT(USP_PAKOL_HAT_BM,H_HelmetB,0.3)
    COMPAT(USP_A2_WATCHCAP,ItemCore,0)
};

class CfgGlasses {
    // Facewear

    // Class declarations
    class None;
    
    COMPAT(USP_RAID_BLK,None,0)
    COMPAT(USP_RAID_SMB1_BLK,None,0)
    COMPAT(USP_RAID_SMB2_BLK,None,0)
    COMPAT(USP_RAID_SMB3_BLK,None,0)
    COMPAT(USP_RAID2_BLK,None,0)
    COMPAT(USP_RAID2_SMB1_BLK,None,0)
    COMPAT(USP_RAID2_SMB2_BLK,None,0)
    COMPAT(USP_RAID2_SMB3_BLK,None,0)
    COMPAT(USP_FM12_BLK,None,0)
    COMPAT(USP_M50_BLK,None,0)
    COMPAT(USP_M50_FC_BLK,None,0)
    COMPAT(USP_BALACLAVA_BLK,None,0)
    COMPAT(USP_BALACLAVA2,None,0)
    COMPAT(USP_BALACLAVA_ADV_SMB1_BLK,None,0)
    COMPAT(USP_BALACLAVA_ADV2_SMB1_BLK,None,0)
    COMPAT(USP_BALACLAVA_ESS_BLK,None,0)
    COMPAT(USP_BALACLAVA_ESS_SMB1_BLK,None,0)
    COMPAT(USP_BALACLAVA_OAK_BLK,None,0)
    COMPAT(USP_BALACLAVA_OAK_SMB1_BLK,None,0)
    COMPAT(USP_ADVANCER,None,0)
    COMPAT(USP_CROSSBOW_BLK,None,0)
    COMPAT(USP_FORETREX,None,0)
    COMPAT(USP_GATORZ_BLK,None,0)
    COMPAT(USP_GATORZ2_BLK,None,0)
    COMPAT(USP_OAKLEY_SI2,None,0)
    COMPAT(USP_DETCORD_BLK,None,0)
    COMPAT(USP_DETCORD2_BLK,None,0)
    COMPAT(USP_MFRAME_BLK,None,0)
    COMPAT(USP_MFRAME2_BLK,None,0)
    COMPAT(USP_MFRAME2_SMB1_BLK,None,0)
    COMPAT(USP_MFRAME2_SMB2_BLK,None,0)
    COMPAT(USP_MFRAME2_SMB3_BLK,None,0)
    COMPAT(USP_STRAIGHTJACKET_BLK,None,0)
    COMPAT(USP_STRAIGHTJACKET2_BLK,None,0)
    COMPAT(USP_STRAIGHTJACKET2_SMB2_BLK,None,0)
    COMPAT(USP_STRAIGHTJACKET2_SMB3_BLK,None,0)
    COMPAT(USP_ROMCO_BCG,None,0)
    COMPAT(USP_SHEMAGH_HEAD,None,0)
    COMPAT(USP_SHEMAGH_HEAD2,None,0)
    COMPAT(USP_SHEMAGH_HEAD3,None,0)
    COMPAT(USP_SHEMAGH_HEAD4,None,0)
    COMPAT(USP_SHEMAGH_BLK,None,0)
    COMPAT(USP_SHEMAGH_NECK,None,0)
    COMPAT(USP_SHEMAGH_NECK3,None,0)
    COMPAT(USP_SHEMAGH_NECK4,None,0)
    COMPAT(USP_SHEMAGH_NECK5,None,0)
    COMPAT(USP_SHEMAGH_NECK6,None,0)
    COMPAT(USP_SHEMAGH_NECK7,None,0)
    COMPAT(USP_SHEMAGH_NECK8,None,0)
    COMPAT(USP_SHEMAGH_NECK9,None,0)
    COMPAT(USP_SUUNTO_BLK,None,0)
    COMPAT(USP_BEARD_BLK,None,0)
    COMPAT(USP_BEARD2_BLK,None,0)
    COMPAT(USP_WRISTCOACH_BLK,None,0)
    COMPAT(USP_THERMAL,None,0)
    COMPAT(USP_THERMAL_AO,None,0)
    COMPAT(USP_THERMAL_AO_GF,None,0)
    COMPAT(USP_THERMAL_AO_GF_WM,None,0)
    COMPAT(USP_THERMAL_AO_WM,None,0)
    COMPAT(USP_THERMAL_GF,None,0)
    COMPAT(USP_THERMAL_GF_WM,None,0)
    COMPAT(USP_THERMAL_WM,None,0)
    COMPAT(USP_WRISTMAP,None,0)
    
};